name: fleet

include:
  - ../../services/common/backbone/compose.yaml
  - ../../services/common/telemetry/compose.yaml
  - ../../services/galleries/compose.yaml

services:

  # start multiple replicas via `dc up -d --scale thumbnailer=3`
  thumbnailer:
    environment:
      - 'OTEL_ENABLED=true'

networks:
  default:
    name: fleet_m4
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
