name: fleet

include:
  - ../../services/common/backbone/compose.yaml
  - ../../services/common/telemetry/compose.yaml
  - ../../services/galleries/compose.yaml

services:
  thumbnailer:
    environment:
      - 'OTEL_ENABLED=true'
    volumes:
      - '${GL_PATH_ORIGINALS}:/media/originals:ro'
      - '${GL_PATH_THUMBS}:/media/thumbs'

  galleries:
    volumes:
      - galleries_data:/mnt/runtime
      - '${GL_PATH_ORIGINALS}:/media/originals:ro'

volumes:
  galleries_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
